# 00. PyTorch Fundamentals

## อะไรคือ PyTorch?

[PyTorch](https://pytorch.org/) เป็น open source machine learning and deep learning framework.

## Pytorch ใช้สำหรับทำอะไร?

PyTorch ช่วยให้สามารถจัดการและประมวลผลข้อมูลและเขียนอัลกอริธึมการเรียนรู้ของเครื่องโดยใช้โค้ดภาษา Python

## ใครบ้างที่ใช้ Pytorch?

บริษัทเทคโนโลยีรายใหญ่ของโลกหลายแห่ง เช่น Meta (Facebook), Tesla และ Microsoft รวมถึงบริษัทวิจัยปัญญาประดิษฐ์ เช่น OpenAI ใช้ PyTorch เพื่อในการ Research แทบทั้งหมด

![PyTorch ถูกใช้อย่างแพร่หลายในอุตสาหกรรมและการวิจัย](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-being-used-across-research-and-industry.png)

ตัวอย่างเช่น Andrej Karpathy (หัวหน้าฝ่าย AI ที่ Tesla) ได้กล่าวสุนทรพจน์หลายครั้ง ([PyTorch DevCon 2019](https://youtu.be/oBklltKXtDE), [Tesla AI Day 2021](https://youtu.be/j0z4FweCy4M?t=2904)) เกี่ยวกับวิธีที่ Tesla ใช้ PyTorch ในงานของ computer vision สำหรับรถขับเคลื่อนอัตโนมัติ


PyTorch ยังถูกใช้งานในอุตสาหกรรมอื่น ๆ เช่น การเกษตรเพื่อ [Computer vision บนรถแทรกเตอร์](https://medium.com/pytorch/ai-for-ag-production-machine-learning-for-agriculture-e8cfdb9849a1).

## ทำไมต้อง PyTorch?

นักวิจัยด้านการ Macinhe Learning นิยมใช้ PyTorch โดยนับตั้งแต่เดือนกุมภาพันธ์ 2022 PyTorch เป็น [framework machine learning ที่ถูกใช้งานมากที่สุดบน Papers With Code](https://paperswithcode.com/trends), เป็นเว็บไซต์สำหรับติดตามงานวิจัยด้าน machine learning และที่เก็บโค้ดที่แนบมากับงานวิจัยเหล่านั้น

PyTorch ยังช่วยใน optimize ภายในตัว เช่น การเร่งความเร็วด้วย GPU (ทำให้โค้ดทำงานได้เร็วขึ้น)


ดังนั้นคุณจึงสามารถมุ่งเน้นไปที่การจัดการข้อมูลและการเขียนอัลกอริธึมได้ และ PyTorch จะช่วยให้มั่นใจว่าโค้ดของคุณทำงานได้อย่างรวดเร็ว

และหากบริษัทอย่าง Tesla และ Meta (Facebook) ใช้ PyTorch เพื่อสร้างโมเดลที่นำไปใช้ในแอปพลิเคชันหลายร้อยแอป ขับเคลื่อนรถยนต์นับพันคัน และได้ใช้กับโปรเจคอื่นๆ รวมเป็นผู้คนนับพันล้านคน แสดงว่า PyTorch มีความสามารถในด้านการพัฒนาอย่างชัดเจนเช่นกัน

## สิ่งที่เราจะมาเรียนรู้กัน


คอร์สนี้ถูกแบ่งออกเป็นส่วนต่าง ๆ (Notebook)

แต่ละ Notebook จะครอบคลุมถึงแนวคิดและแนวความคิดที่สำคัญภายใน PyTorch โน้ตบุ๊กต่อมาจะพัฒนาความรู้จากโน้ตบุ๊กก่อนหน้า (เริ่มต้นที่ 00, 01, 02 เรื่อยๆ)

Notebook นี้เกี่ยวกับหลักสูตรพื้นฐานของ Machine Learning และ Deep Learning ที่ชื่อว่า Tensor

โดยเฉพาะเราจะพูดถึง:

| **Topic** | **Contents** |
| ----- | ----- |
| **Introducing tensors** | Tensors เป็นหลักประกอบพื้นฐานของ machine learning and deep learning. |
| **How to create tensors** | Tensors สามารถ represent ข้อมูลได้แทบทุกอย่าง  (รูป, คำ, ตารางข้อมูลตัวเลข). |
| **Getting information from tensors** | Tensor สามารถเอาข้อมูลใส่ลงไปได้ และ เอาข้อมูลออกมาได้เช่นกัน |
| **Manipulating tensors** | Machine learning algorithms (เช่น neural networks) เกิดจากการรวมตัวของ operation ใน tensor เช่น adding, multiplying, combining. |
| **Dealing with tensor shapes** | ปัญหาที่เวลาใช้ tensor ส่วนใหญ่จะเจอเป็น Shape mismatch (พยายามที่จะรวม tensor ที่ shape ไม่ตรงกันเข้าด้วยกัน). |
| **Indexing on tensors** | ถ้าหากเคยใช้ indexed on a Python list or NumPy array แล้วมันก็จะคล้ายกับ tensors อย่างมากแต่ต่างกันตรงที่ tensors จะมีมิติมากกว่ามากๆ |
| **Mixing PyTorch tensors and NumPy** | ใน PyTorch เราสามารถเล่นกับ tensors ([`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html)) หรือ tensor NumPy arrays ([`np.ndarray`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)) โดยเราสามารถเอามาใช้ด้วยกันได้|
| **Reproducibility** | Machine learning ส่วนใหญ่เกิดจากการ *ส่มค่า* แต่ว่ามีทีเราต้องการที่จะเปลี่ยนการ *สุ่มค่า* ให้ไม่ random 100%|

## ถ้าติดปัญหาทำยังไง?

todo แปะลิ้ง:



สามารถถามได้ที่ [Discussions page](https://github.com/mrdbourke/pytorch-deep-learning/discussions)

และ [PyTorch developer forums](https://discuss.pytorch.org/), สำหรับการอ่าน forum ที่เคยเจอ bug คล้ายๆกัน

## Importing PyTorch

> **Note:** ก่อนที่จะรันโค้ดใน notebook นี้แนะนำว่าให้ดู Docs ของ pytorch ด้วย [PyTorch setup steps](https://pytorch.org/get-started/locally/).
>
> แต่ว่า, **ถ้ารันใน Google Colab หรือ Kaggle**, ก็รันได้เลยเพราะมี env มาให้แล้ว.

มาเริ่มกันที่การเช็คเวอร์ชั่นของ pytorch

In [ ]:
import torch
torch.__version__

'2.3.0+cu121'

## Introduction to tensors

หลังจากที่เรา import pytorch มาแล้ว, ได้เวลาที่จะเรียนเกี่ยวกับ Tensors

Tensors เป็นพื้นฐานสุดๆ สำหรับการสร้าง machine learning

มีไว้สำหรับ represent ข้อมูลต่างๆให้เป็นรูปแบบของตัวเลข

ยกตัวอย่างเช่น, รูปภาพสามารถแปลงเป็น tensor ที่มี shape `[3, 224, 224]` นั่นหมายถึง `[colour_channels (RGB), ความสูง, ความกว้าง]`, ก็คือรูปมี `3` colour channels (red, green, blue), สูง`224` pixels  และกว้าง `224` pixels.

![example of going from an input image to a tensor representation of the image, image gets broken down into 3 colour channels as well as numbers to represent the height and width](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png)



### Creating tensors

ถ้าน้องๆสนใจก็สามารถอ่าน docs เพิ่มเติมได้ [documentation `torch.Tensor`](https://pytorch.org/docs/stable/tensors.html).



สิ่งแรกที่เราจะมาสร้างกันก็คือ **scalar**.

Scalar เป็นตัวเลขตัวเดียว ถ้ามองในมุมของ tensor จะมี dimension เป็น 0

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

สังเกตว่าจะได้ output เป็น `tensor(7)`?

นั่นหมายถึง `scalar` เป็นเลขที่เป็น type ของ `torch.Tensor`.

We can check the dimensions of a tensor using the `ndim` attribute.

In [ ]:
scalar.ndim

0

ถ้าเราอยากจะแค่เอาตัวเลขจาก tensor ละ?


โดยการแปลง `torch.Tensor` ให้เป้น integer ใน python

เราสามารถใช่คำสั่ง item() ได้

In [ ]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

ต่อมาเราจะมาดูกันที่ **vector** กัน

vector มี 1 dimension แต่เก็บได้หลากตัวเลข

ยกตัวอย่างเช่น vector [3, 2] เพื่อที่จะให้หมายถึงจำนวน [ห้องนอน, ห้องน้ำ] ในบ้าน หรือ [3, 2, 2] จำนวน [ห้องนอน, ห้องน้ำ, ที่จอดรถ] ในบ้าน

จะเห็นได้ว่า vector จะมีความสามารถในการอธิบายสิ่งต่างๆได้

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])



แล้วเวกเตอร์มีกี่ dimension ละ

In [ ]:
# Check the number of dimensions of vector
vector.ndim

1

เห็นอะไรแปลกๆมั้ยครับ `vector` มี 2 ตัวเลขแต่ทำไมมันมีแค่ 1 dimension กัน

เดียวจะบอกทริคให้ฟัง

สังเกตว่า dimensions ของ tensor pytorch ที่มึ (`[`) เราจำนับทั้งก้อนนั้นเป็น 1 dimension เลย

แล้ว vector มี `[` จำนวนเท่าไหร่ละก็คือ 1 นั้นเอง

เวลาที่ใช้คำสั่ง shape จะบอกข้อมูลที่ถูก arranged แล้ว


In [ ]:
# Check shape of vector
vector.shape

torch.Size([2])

โค้ดข้องบนจะได้  `torch.Size([2])` นั้นหมายถึง vector การดู shape `[2]`.

มาต่อกันที่ **matrix**.

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

จะสังเกตได้ว่า matrix จะมีความยืดหยุ่นมากกว่า เพราะมี dimension มากกว่า

In [ ]:
# Check number of dimensions
MATRIX.ndim

2

`MATRIX` มี 2 dimension (ลองเช็คดูว่ามี [ กี่อัน?).

แล้ว `shape` เป็นเท่าไหร่กันนะ

In [ ]:
MATRIX.shape

torch.Size([2, 2])

จะได้ค่า `torch.Size([2, 2])` หมายถึง `MATRIX`  มี 2 element ในแนวแนวกว้าง

เราจะมาสร้าง **tensor** กัน

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

tensors สามารถ represent ค่าได้เกือบทุกอย่าง


เราอาจจะสร้าง tensors เหมือนเป็นตารางยอดขายสินค้าต่างๆได้

![a simple tensor in google sheets showing day of week, steak sales and almond butter sales](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_simple_tensor.png)

ให้ทายว่า tensors มีกี่ dimensions กัน (ลองนับตรง [ ดู)

In [ ]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

แล้ว shape ละ

In [ ]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

จะได้ output `torch.Size([1, 3, 3])`.

The dimensions go outer to inner.

![example of different tensor dimensions](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

อย่างนี้มีความหมายอยู่ว่าค่าพวก scalars และ vectors จะถูกใช้เป็นตัวพิมเล็กเช่น  `y` หรือ `a` และ matrices และ tensors จะถูกใช้เป็นตัวพิมพ์ใหญ่เช่น `X` หรือ `W`
> **Note:** สังเกตได้ว่าตัวพิมเล็กจะถูกใช้กับ `scalar` และ `vector`และตัวพิมใหญ่จะถูกใช้กับ `MATRIX` และ `TENSOR`. อย่างนี้มีความหมายอยู่ว่าค่าพวก scalars และ vectors จะถูกใช้เป็นตัวพิมเล็กเช่น  `y` หรือ `a` และ matrices และ tensors จะถูกใช้เป็นตัวพิมพ์ใหญ่เช่น `X` หรือ `W`
>

มาสรุปจากที่เรียนก่อนหน้านี้กัน

| Name | What is it? | Number of dimensions | Lower or upper (usually/example) |
| ----- | ----- | ----- | ----- |
| **scalar** | เป็นตัวเลขเดียว | 0 | Lower (`a`) |
| **vector** | ปริมาณทางคณิตศาสตร์ที่มีทิศทาง (e.g. ความเร็วลมพร้อมทิศทาง) และมีได้หลายเลข| 1 | Lower (`y`) |
| **matrix** | array ของตัวเลขที่มี 2 มิติ | 2 | Upper (`Q`) |
| **tensor** | array ของตัวเลขที่มีได้ n มิติ| can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector | Upper (`X`) |

![scalar vector matrix tensor and what they look like](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

### Random tensors

ในการสร้าง tensors ก่อนหน้านี้เราจะใช้ tensors ที่เป็นลักษณะแบบกำหนัดค่าขึ้นมาเองและในการสร้าง machine learning models เช่น neural network จะปรับกอบไปด้วย tensors หลาย shape หลายรูปแบบ ซึ่งเราจะมีการกำหนดค่าของ tensors เองน้อยมาก

โดยในการสร้าง machine learning models เราจะเริ่มจากการ init weight ที่เป็นค่า random ขึ้นมาก่อนแล้วปรับค่าเหล่านั้นเพื่อให้ model ดีขึ้นด้วยอัลกอริทึมต่างๆ

จะประมาณว่า:

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...`


ถ้ามองในมุมของ data scientist เราจะมองทำนองนี้ (initialization), looks at data (representation) and updates (optimization) its random numbers.


ถ้าอย่างงั้นเรามาเริ่มสร้าง random tensors กันเลย!

เราจะใช้ [`torch.rand()`](https://pytorch.org/docs/stable/generated/torch.rand.html) และใส่ค่า `size` ใน parameter.

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.4758, 0.0401, 0.7584, 0.7365],
         [0.1942, 0.6436, 0.2718, 0.2011],
         [0.7617, 0.0694, 0.1354, 0.8651]]),
 torch.float32)

ข้อดีความยือหยุ่นของ `torch.rand()`คือเราสามารถปรับ `size` ให้เป็นเท่าไหร่ก็ได้ที่ต้องการ

เช่นถ้าเกิดเราต้องการสร้างรูปเราก็จะใช้ shape
`[224, 224, 3]` (`[height, width, color_channels`]).

In [ ]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

บางครั้งเราก็ต้องการค่า tensors ที่มีเฉพาะ 0 หรือ 1

ซึ่งจะเป็นเทคนิคสำหรับการ masking ค่า (เหมือนกับว่าเราจะต้องการให้ค่าไหนมี value และค่าไหนไม่มี value เพื่อที่จะทำให้ model ไม่เรียนรู้มัน)

ในการสร้างเราจะใช้คำสั่ง [`torch.zeros()`](https://pytorch.org/docs/stable/generated/torch.zeros.html)

และเราสามารถปรับค่า `size` parameter ได้ตามที่ต้องการ

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

ในการทำเราจะสร้าง tensors ที่มีแต่ 1 ก็ใช้คำสั่ง [`torch.ones()` ](https://pytorch.org/docs/stable/generated/torch.ones.html) ได้เลย

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range and tensors like

ถ้าเกิดว่าอยากที่จะสร้างตัวเลขที่มี range เยอะเช่น 1 ถึง 100

เราสามารถใช้คำสั่ง `torch.arange(start, end, step)` ได้


โดย:
* `start` = ค่าที่ต้องการเริ่ม (e.g. 0)
* `end` = ค่าที่ต้องการจบ (e.g. 10)
* `step` = เราจะเพิ่มค่านั้นที่ละเท่าไหร่ (e.g. 1)

In [ ]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-20-a404776195c1>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use [`torch.zeros_like(input)`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html) or [`torch.ones_like(input)`](https://pytorch.org/docs/1.9.1/generated/torch.ones_like.html) which return a tensor filled with zeros or ones in the same shape as the `input` respectively.

In [ ]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes


มีหลายประเภทของ [tensor datatypes ที่ใช้ได้ใน PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types).

บางประเภทเหมาะสำหรับ CPU และบางประเภทเหมาะสำหรับ GPU

การทำความเข้าใจว่าแต่ละประเภทคืออะไรอาจใช้เวลาสักหน่อย

โดยทั่วไปแล้วถ้าคุณเห็น torch.cuda อยู่ที่ไหน นั่นหมายถึง tensor นั้นถูกใช้สำหรับ GPU (เนื่องจาก Nvidia GPUs ใช้ toolkit สำหรับคำนวณที่เรียกว่า CUDA)

ประเภทที่พบบ่อยที่สุด (และเป็นค่าเริ่มต้นทั่วไป) คือ torch.float32 หรือ torch.float

ซึ่งเรียกว่า "32-bit floating point"

แต่ก็ยังมี 16-bit floating point (torch.float16 หรือ torch.half) และ 64-bit floating point (torch.float64 หรือ torch.double)

และยังมีความซับซ้อนมากขึ้นอีกโดยยังมี integers ขนาด 8-bit, 16-bit, 32-bit และ 64-bit

และยังมีอีกมากมาย!

> **Note:** integer คือเลขจำนวนเต็ม เช่น `7` ในขณะที่ float มีจุดทศนิยม เช่น `7.0`.

เหตุผลที่มีหลายประเภทพวกนี้เกี่ยวข้องกับ  **precision in computing**.

เพราะความแม่นยำคือปริมาณรายละเอียดที่ใช้ในการอธิบายตัวเลข

ค่าความแม่นยำที่สูงขึ้น (8, 16, 32) มีรายละเอียดมากขึ้นและดังนั้นจึงใช้ข้อมูลมากขึ้นในการแสดงตัวเลข

เรื่องนี้สำคัญใน deep learning และการคำนวณทางตัวเลขเพราะคุณต้องทำการคำนวณหลายๆ อย่าง ยิ่งมีรายละเอียดมากเท่าไหร่ก็ยิ่งใช้การคำนวณมากขึ้นเท่านั้น

ดังนั้น datatypes ที่มีความแม่นยำต่ำกว่ามักจะคำนวณได้เร็วกว่าแต่แลกกับประสิทธิภาพที่ต่ำลงในตัวชี้วัดเช่นความแม่นยำ (คำนวณได้เร็วกว่าแต่แม่นยำน้อยลง)

> **Resources:**
  * [PyTorch documentation for a list of all available tensor datatypes](htt
  ps://pytorch.org/docs/stable/tensors.html#data-types).
  * [Wikipedia page for an overview of what precision in computing](https://en.wikipedia.org/wiki/Precision_(computer_science)) is.

มาดูกันว่าเราจะสร้าง tensors ด้วย datatypes เฉพาะได้อย่างไร เราสามารถทำได้โดยใช้พารามิเตอร์ `dtype`

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

นอกจากปัญหาเรื่อง shape (รูปแบบของ tensor ไม่ตรงกัน) ปัญหาที่พบบ่อยอีกสองอย่างใน PyTorch คือปัญหาเรื่อง datatype และ device

ตัวอย่างเช่น หนึ่งใน tensor เป็น `torch.float32` และอีกหนึ่งเป็น `torch.float16` (PyTorch มักต้องการให้ `tensors` มีรูปแบบเดียวกัน)

หรือหนึ่งใน tensor อยู่บน CPU และอีกหนึ่งอยู่บน GPU (PyTorch ต้องการให้การคำนวณระหว่าง tensors อยู่บนอุปกรณ์เดียวกัน)

เราจะเห็นเรื่องการใช้งานอุปกรณ์ (device) มากขึ้นในภายหลัง

ตอนนี้มาสร้าง tensor ด้วย `dtype=torch.float16` กัน

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

## Getting information from tensors

เมื่อสร้าง tensors ขึ้นมาแล้ว (หรือคนอื่นหรือโมดูล PyTorch สร้างขึ้นมาให้) อาจต้องการดึงข้อมูลบางอย่างจากมัน

เราเคยเห็นสิ่งเหล่านี้มาก่อน แต่คุณสมบัติที่พบได้บ่อยที่สุดสามอย่างที่คุณอาจต้องการทราบเกี่ยวกับ tensors คือ:

`shape` - tensor มีรูปแบบอย่างไร? (บางการดำเนินการต้องการกฎรูปแบบเฉพาะ)
`dtype` - องค์ประกอบภายใน tensor ถูกจัดเก็บในรูปแบบข้อมูลใด?
`device` - tensor ถูกจัดเก็บในอุปกรณ์อะไร? (ปกติจะเป็น GPU หรือ CPU)
มาสร้าง tensor แบบสุ่มแล้วหาข้อมูลเกี่ยวกับมันกัน

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.4076, 0.1076, 0.6742, 0.2798],
        [0.4752, 0.7375, 0.4973, 0.3623],
        [0.6723, 0.3057, 0.3841, 0.3233]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating tensors (tensor operations)

ใน deep learning ข้อมูล (รูปภาพ, ข้อความ, วิดีโอ, เสียง, โครงสร้างโปรตีน ฯลฯ) จะถูกแทนด้วย tensors

model เรียนรู้จาก tensors เหล่านั้นและทำ operation การหลายๆ อย่าง (อาจจะเป็นล้านๆ ครั้ง) บน tensors เพื่อสร้างการแสดงผลของรูปแบบในข้อมูลอินพุต

การดำเนินการเหล่านี้มักจะเกิดจากการผสมผสาน operation ระหว่าง:

การบวก
การลบ
การคูณ (แบบ element-wise)
การหาร
การคูณเมทริกซ์
และนั่นคือทั้งหมด แน่นอนว่ามีอีกไม่กี่อย่างแต่เหล่านี้คือส่วนประกอบพื้นฐานของ neural networks

การเรียงลำดับส่วนประกอบเหล่านี้อย่างถูกต้อง คุณสามารถสร้าง neural networks ที่ซับซ้อนที่สุดได้ (เหมือนกับการต่อเลโก้เลย!)

### Basic operations

มาเริ่มต้นกับการทำงานพื้นฐาน เช่น การบวก (+), การลบ (-), และ การคูณ (*)

มันก็ทำงานเหมือนที่เราเรียนมากันเลย

In [ ]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

สังเกตว่าค่า tensor ด้านบนไม่ได้เป็น `tensor([110, 120, 130])` เป็นเพราะค่าภายใน tensor จะไม่เปลี่ยนแปลงนอกจากถ้าจะทำการกำหนดค่าใหม่

In [ ]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

เราจะลบออก พร้อมกับการ reassign ตัวแปร `tensor`  

In [ ]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

PyTorch  ยังมีฟังก์ชันที่ใช้งานง่ายมากมาย เช่น [`torch.mul()`](https://pytorch.org/docs/stable/generated/torch.mul.html#torch.mul)(ย่อมาจากการคูณ) และ [`torch.add()`](https://pytorch.org/docs/stable/generated/torch.add.html) เพื่อทำการดำเนินการพื้นฐานได้เลย

In [ ]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

แต่วิธีที่พบมากกว่าในการใช้งานคือการใช้สัญลักษณ์ของตัวดำเนินการเช่น`*`  แทนที่จะใช้ `torch.mul()`

In [ ]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Matrix multiplication (is all you need)

หนึ่งใน operation ที่ใช้บ่อยมากๆๆๆ ในทาง machine learning และ deep learning algorithms (เหมือน neural networks ) คือ [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

ใน pytorch มีการ implements matrix multiplication โดยการใช้คำสั่ง [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html)

กฎในการ matrix multiplication คือ

1. จำนวนหลักของเมทริกซ์ตัวหน้าต้อง เท่ากับ จำนวนแถวของเมทริกซ์ตัวหลัง:
  * `(3, 2) @ (3, 2)` ไม่ได้
  * `(2, 3) @ (3, 2)` ได้
  * `(3, 2) @ (2, 3)` ได้
2. มิติของเมทริกซ์ผลลัพธ์จะเท่ากับ จำนวนแถวของตัวหน้าคูณจำนวนหลักของตัวหลัง:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

> **Note:** "`@`" ใน Python เป็นสัณลักษณะสำหรับการทำ matrix multiplication.

> **Resource:** เราสามารถดู กฎสำหรับ matrix multiplication ด้วย `torch.matmul()` ได้ที่ [PyTorch documentation](https://pytorch.org/docs/stable/generated/torch.matmul.html).



In [ ]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

ความต่างระหว่าง element-wise multiplication กับ matrix multiplication

ถ้าเรามีค่า `tensor`  `[1, 2, 3]`:

| Operation | Calculation | Code |
| ----- | ----- | ----- |
| **Element-wise multiplication** | `[1*1, 2*2, 3*3]` = `[1, 4, 9]` | `tensor * tensor` |
| **Matrix multiplication** | `[1*1 + 2*2 + 3*3]` = `[14]` | `tensor.matmul(tensor)` |


In [ ]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

จริงๆแล้ว สามารถคูณเมทริกซ์ด้วยมือได้นะ แต่ไม่แนะนำ55

ใช้ `torch.matmul()` จะเร็วกว่า

In [ ]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.69 ms, sys: 0 ns, total: 1.69 ms
Wall time: 1.8 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 128 µs, sys: 0 ns, total: 128 µs
Wall time: 134 µs


tensor(14)

## One of the most common errors in deep learning (shape errors)

เนื่องจากส่วนใหญ่ของ deep learning เป็นการคูณและดำเนินการบนเมทริกซ์ และเมทริกซ์มีกฎ เกี่ยวกับรูปร่างและขนาดที่สามารถรวมกันได้ หนึ่ง error ที่พบบ่อยที่สุดใน deep learning คือการไม่ตรงกันของรูปร่าง (shape mismatches)

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We can make matrix multiplication work between `tensor_A` and `tensor_B` by making their inner dimensions match.

One of the ways to do this is with a **transpose** (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:
* `torch.transpose(input, dim0, dim1)` - where `input` is the desired tensor to transpose and `dim0` and `dim1` are the dimensions to be swapped.
* `tensor.T` - where `tensor` is the desired tensor to transpose.

Let's try the latter.

In [ ]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [ ]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


You can also use [`torch.mm()`](https://pytorch.org/docs/stable/generated/torch.mm.html) which is a short for `torch.matmul()`.

In [ ]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

ถ้าไม่มีการสลับเมทริกซ์ (transpose) กฎของการคูณเมทริกซ์จะไม่ถูกต้องและจะเกิดข้อผิดพลาดเหมือนที่เห็นข้างบน

เอาแบบภาพอธิบายดีไหม?

![visual demo of matrix multiplication](https://github.com/mrdbourke/pytorch-deep-learning/raw/main/images/00-matrix-multiply-crop.gif)

You can create your own matrix multiplication visuals like this at http://matrixmultiplication.xyz/.

> **Note:** A matrix multiplication like this is also referred to as the [**dot product**](https://www.mathsisfun.com/algebra/vectors-dot-product.html) of two matrices.



Neural networks เต็มไปด้วยการคูณเมทริกซ์และการ dot products

The [`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html) (เราจะได้เห็นในภายหลัง) หรือที่รู้จักกันว่า feed-forward layer หรือ fully connected layer จะทำการคูณเมทริกซ์ระหว่างอินพุต  `x` และเมทริกซ์ weight`A`.

$$
y = x\cdot{A^T} + b
$$

ซึ่ง:
* `x` คืออินพุตของเลเยอร์ (การเรียนรู้เชิงลึกคือการซ้อนกันของเลเยอร์ต่างๆ เช่น `torch.nn.Linear()` และอื่นๆ ที่ต่อกัน).
* `A` คือเมทริกซ์น้ำหนักที่ถูกสร้างโดยเลเยอร์ ซึ่งเริ่มต้นจากตัวเลขสุ่มที่ถูกปรับปรุงเมื่อ neural network เรียนรู้ที่จะสื่อถึงรูปแบบในข้อมูลได้ดีขึ้น (สังเกต "`T`" นั่นคือเพราะเมทริกซ์ weightถูกสลับเมทริกซ์)
  * **Note:** อาจเห็น`W` หรืออักษรอื่นๆ เช่น  `X` ใช้เพื่อแสดงเมทริกซ์ weight
* `b` คือค่าลำเอียง (bias) ที่ใช้เพื่อปรับน้ำหนักและอินพุตเล็กน้อย
* `y` คือเอาต์พุต (การปรับแต่งอินพุตเพื่อหวังจะค้นหารูปแบบในนั้น)

นี่คือฟังก์ชันเชิงเส้น (อาจเคยเห็นบางอย่างเช่น $y = mx+b$ ในโรงเรียนหรือที่อื่น) และสามารถใช้เพื่อวาดเส้นตรงได้!

มาลองเล่นกับ linear layer กัน

ลองเปลี่ยนค่าของ `in_features` และ  `out_features` ด้านล่างแล้วดูว่าจะเกิดอะไรขึ้น

สังเกตอะไรเกี่ยวกับรูปร่างบ้างไหม?

In [ ]:
tensor_A

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=1) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[1.5488],
        [3.8038],
        [6.0588]], grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 1])


In [ ]:
output

tensor([[1.5488],
        [3.8038],
        [6.0588]], grad_fn=<AddmmBackward0>)

ถ้าไม่เคยทำมันมาก่อน, การคูณเมทริกซ์อาจเป็นเรื่องที่งงๆ ในตอนแรก

แต่พอได้ลองเล่นกับมันหลายครั้งแล้ว และอาจจะได้เจอ neural networks บ้าง จะเห็นว่ามันคล้ายๆกันไปหมดเลย

matrix multiplication is all you need.
![matrix multiplication is all you need](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_matrix_multiplication_is_all_you_need.jpeg)

*When you start digging into neural network layers and building your own, you'll find matrix multiplications everywhere. **Source:** https://marksaroufim.substack.com/p/working-class-deep-learner*

### Finding the min, max, mean, sum, etc (aggregation)

ตอนนี้หลังจากที่เราเห็นวิธีการจัดการ tensors บ้างแล้ว, มาดูวิธีการรวมพวกเข้าด้วยกันบ้าง (ทำให้มีค่าน้อยลง)

เริ่มต้นจากการสร้าง tensor แล้วหาค่าสูงสุด (max), ต่ำสุด (min), ค่าเฉลี่ย (mean), และผลรวม (sum) ของมันดูครับ





In [ ]:
# Create a tensor
x = torch.arange(0, 110, 10)
x

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

ใช้ tensor ที่เราสร้างไว้เพื่อหาค่าสูงสุด (max), ต่ำสุด (min), ค่าเฉลี่ย (mean), และผลรวม (sum)

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 100
Mean: 50.0
Sum: 550


> **Note:** บางกรณีเช่น คำสั่ง `torch.mean()` อาจต้องการให้ tensors เป็นชนิดข้อมูล `torch.float32` หรือชนิดข้อมูลอื่นๆ ที่ระบุไว้เป็นเงื่อนไข มิฉะนั้นการดำเนินการอาจล้มเหลวได้ครับ

สามารถทำเหมือนเดิมด้วยเมทอด `torch` ได้เช่นกัน

In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(100, tensor(0), tensor(50.), tensor(550))

### Positional min/max

สามารถหาค่า index ของ tensor ที่มีค่าสูงสุดหรือต่ำสุดได้ด้วย[`torch.argmax()`](https://pytorch.org/docs/stable/generated/torch.argmax.html) และ [`torch.argmin()`](https://pytorch.org/docs/stable/generated/torch.argmin.html) respectively.

การนี้จะช่วยให้ได้แค่ตำแหน่งที่มีค่าสูงสุด (หรือต่ำสุด) โดยไม่ต้องได้ค่ามันมาจริงๆ


In [ ]:
# Create a tensor
tensor = torch.arange(0, 200, 5)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")


Tensor: tensor([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135,
        140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195])
Index where max value occurs: 39
Index where min value occurs: 0


### Change tensor datatype

เหมือนกับที่พูดเอาไว้ก้อนหน้า ปัญหาที่พบบ่อยในการดำเนินการ deep learning คือการมี tensors ที่มีประเภทข้อมูล (datatypes)ต่างกัน

ถ้า tensor หนึ่งเป็น `torch.float64` และอีกตัวเป็น `torch.float32`, อาจเกิด error ได้

แต่มีวิธีแก้ไข

เราสามารถเปลี่ยนประเภทข้อมูลของ tensors โดยใช้
[`torch.Tensor.type(dtype=None)`](https://pytorch.org/docs/stable/generated/torch.Tensor.type.html) โดยที่`dtype` เป็นประเภทของข้อมูลที่คุณต้องการใช้

เริ่มต้นจากการสร้าง tensor แล้วตรวจสอบประเภทของข้อมูล (ค่าเริ่มต้นคือ`torch.float32`).

In [ ]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [ ]:
tensor

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])

ตอนนี้เราจะสร้าง tensor อีกตัวที่เหมือนเดิม แต่เปลี่ยนประเภทข้อมูลให้เป็น `torch.float16`



In [ ]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16


tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

And we can do something similar to make a `torch.int8` tensor.

In [ ]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

> **Note:** ประเภทข้อมูลที่แตกต่างกันอาจทำให้สับสนในตอนแรก แต่คิดว่าเป็นแบบนี้, ตัวเลขที่น้อยลง (เช่น 32, 16, 8) จะทำให้คอมพิวเตอร์เก็บค่าได้ไม่แม่นยำเท่าไหร่ และด้วยจำนวนพื้นที่ที่น้อยลงนี้, มักจะทำให้คำนวณเร็วขึ้นและลดขนาด model โดยรวมลงไป

 Neural networks บนโทรศัพท์มักจะใช้ integer 8-bit, ที่เล็กกว่าและทำงานได้เร็วกว่า แต่ก็ไม่แม่นยำเท่ากับ float32 counterparts สำหรับข้อมูลเพิ่มเติมคุณสามารถอ่านเพิ่มเติมได้ที่ [precision in computing](https://en.wikipedia.org/wiki/Precision_(computer_science)).


### Reshaping, stacking, squeezing and unsqueezing

โดจปกติเราจะนิยมเปลี่ยน shape ของข้อมูลกันและต้องเปลี่ยน tensors โดยที่ไม่เปลี่ยนแปลงค่าภายใน

ซึ่งมีวิธีหลักๆดังนี้

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | เปลี่ยนรูปร่างของ `input` to `shape`  (ถ้าเข้ากันได้), สามารถใช้ `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. |
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. |

ทำไมต้องใช้วิธีแบบนี้?

เพราะโมเดล deep learning (neural networks) เกี่ยวกับการจัดการ tensors ในทางต่างๆ และเนื่องจากกฎของการคูณเมทริกซ์ หากมีข้อผิดพลาดเกี่ยวกับรูปร่างที่ไม่ตรงกัน อาจพบerror การใช้ method เหล่านี้ช่วยให้มั่นใจได้ว่าสมาชิกที่ถูกต้องของ tensors ของกำลังทำ operation กับสมาชิกที่ถูกต้องตามกฎการคูณของ tensors อื่นๆ

มาลองเริ่มต้นด้วยการสร้าง tensor กัน

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

ตอนนี้เราจะเพิ่มมิติเพิ่มเติมด้วย `torch.reshape()`.

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

เรายังสามารถเปลี่ยนมุมมองด้วย `torch.view()`.

In [ ]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

อย่าลืมนะว่า การเปลี่ยนมุมมองของ tensor ด้วย torch.view() จริงๆ แล้วสร้างมุมมองใหม่ของ "tensor เดียวกัน"

ดังนั้นการเปลี่ยนมุมมองจะเปลี่ยน tensor ต้นฉบับไปด้วย

In [ ]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([1., 2., 3., 4., 5., 6., 7.]))

ถ้าเราต้องการนำ tensor ใหม่ของเรามารวมกันให้ได้ห้าชั้น เราสามารถทำได้ด้วย  `torch.stack()`.

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [ ]:
x_stacked.shape

torch.Size([7, 4])

ถ้าต้องการลบมิติเดียวจาก tensor ทั้งหมดละ?

สามารถใช้ `torch.squeeze()`

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])


In [ ]:
# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


และหากต้องการทำการกลับกันของ torch.squeeze() สามารถใช้ torch.unsqueeze()

In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


อีกทั้งยังสามารถจัดเรียงลำดับค่าแกนด้วย `torch.permute(input, dims)` โดยที่ input จะได้รับการเปลี่ยนเป็น มุมมอง ใหม่ตาม dims

In [ ]:
x_original = torch.rand(size=(229, 224, 3))
x_original.shape

torch.Size([229, 224, 3])

In [ ]:
# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([229, 224, 3])
New shape: torch.Size([3, 229, 224])


## Indexing (selecting data from tensors)

บางครั้งเราก็อาจต้องการเลือกข้อมูลที่เฉพาะเจาะจงจาก tensors (เช่นเพียง columns แรกหรือแถวที่สอง)

ในการทำเช่นนั้น คุณสามารถใช้การ indexing

หากเคยทำการ indexing ใน Python lists หรือ NumPy arrays, การ indexing ถึงใน PyTorch ด้วย tensors จะคล้ายกันมาก

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

การ indexing จะไปตามลำดับ dimension ภายนอก -> dimension ภายใน (ดูที่เครื่องหมายวงเล็บสี่เหลี่ยม `[`).

In [ ]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


และยังสามารถใช้ `:` เพื่อระบุ "ค่าทั้งหมดใน dimension นี้" และใช้เครื่องหมายจุลภาค (`,`) เพื่อเพิ่มมิติอื่นๆ

In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:,:2]

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

## PyTorch tensors & NumPy

เนื่องจาก NumPy เป็นไลบรารีการคำนวณตัวเลขของ Python ที่นิยม PyTorch มีความสามารถในการทำงานร่วมกับ NumPy ได้อย่างดี

สอง method หลักที่ต้องใช้สำหรับการแปลง NumPy เป็น PyTorch (แปลงได้ทั้ง 2 ทางไป-กลับ) คือ:

* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - NumPy array -> PyTorch tensor.
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - PyTorch tensor -> NumPy array.

มาลองใช้กัน

In [ ]:
import numpy as np
array = np.arange(1.0, 8.0)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)


tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

> **Note:** โดยค่า default NumPy arrays จะถูกสร้างขึ้นด้วยประเภทข้อมูล float64 และหากแปลงมันเป็น PyTorch tenso มันจะยังคงรักษาประเภทข้อมูลเดิม (เช่นเดียวกับที่แสดงข้างบน)
>
> อย่างไรก็ตาม, การคำนวณใน PyTorch มักใช้  `float32` เป็นค่า default
>
> ดังนั้นหากต้องการแปลง NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32) สามารถใช้ `tensor = torch.from_numpy(array).type(torch.float32)`.

In [ ]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

หากต้องการที่จะเปลี่ยนจาก PyTorch tensor เป็น NumPy array สามารถเรียกใช้ `tensor.numpy()`.

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

หากเปลี่ยนแปลง tensor ต้นฉบับ numpy_tensor ใหม่จะยังคงเดิม

In [ ]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

เมื่อเรียนรู้เพิ่มเติมเกี่ยวกับ neural networks และ machine learning ไปเรื่อยๆจะเริ่มสังเกตเห็นถึงความสำคัญของความสุ่ม

ความสุ่มแบบ pseudorandom (การสุ่มเทียม) นั่นเอง เพราะในทางทฤษฎีคณิตศาสตร์ คอมพิวเตอร์มีลักษณะเป็น deterministic (รันซ้ำแล้วได้ผลเดิม) ดังนั้นความสุ่มที่เกิดขึ้นคือการสร้างความสุ่มที่จำลอง [ดู ref จาก 9arm ได้ครับ "RNG: ศาสตร์แห่งเกลือ"](https://www.youtube.com/watch?v=12FhEYEgfo8&ab_channel=9arm)

ความสัมพันธ์นี้เกี่ยวข้องกับ neural networks และ deep learning ยังไงละ

ในช่วง random tensors เราได้พูดถึงว่า neural networks เริ่มต้นด้วยตัวเลขสุ่มเพื่อ represent รูปแบบในข้อมูล และพยายามปรับปรุงตัวเลขสุ่มเหล่านั้นโดยใช้ operation บน tensors  เพื่อที่จะrepresent แบบในข้อมูลได้ดีขึ้น

แบบสั้นๆ:

``เริ่มต้นด้วยตัวเลขสุ่ม -> การดำเนินการบน tensors -> พยายามทำ represent ได้ดีขึ้น (ทำซ้ำไปเรื่อยๆ)``

แม้ว่าความสุ่มจะมีประโยชน์และมีพลัง แต่ก็บางครั้งอาจต้องการมีความสุ่มน้อยลง

ทำไมถึงต้องลดการสุ่มให้น้อยลง?

เพราะ "เพื่อที่จะทำการทดลองที่สามารถทำซ้ำได้"

เช่น คุณได้สร้างอัลกอริธึมที่สามารถทำให้ได้ผลลัพธ์ X

แล้วเพื่อนก็ลองเอามารัน ปรากฎว่าได้ผลลัพธ์ที่ไม่ใช่ X ละ...

เราจะแก้ปัญหานี้ยังไงดี?

เรากจะเรียกว่าการ **reproducibility**

นั่นคือ คุณสามารถได้ผลลัพธ์เดียวกัน (หรือใกล้เคียงกัน) บนคอมพิวเตอร์ของคุณโดยใช้โค้ดเดียวกันที่ได้รับบนคอมพิวเตอร์ของเรา

มาดูตัวอย่างย่อของ reproducibility ใน PyTorch กัน

เราจะเริ่มต้นด้วยการสร้าง tensor สุ่มสองตัว เนื่องจากมันเป็นสุ่ม แสดงว่าไม่ควรจะไม่เหมือนกันใช่มั้ย?

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.0812, 0.4171, 0.6363, 0.1527],
        [0.7885, 0.6420, 0.6613, 0.5735],
        [0.2508, 0.2234, 0.7855, 0.8276]])

Tensor B:
tensor([[0.2666, 0.9653, 0.1008, 0.6585],
        [0.1411, 0.1986, 0.8869, 0.9825],
        [0.6363, 0.2474, 0.6804, 0.4681]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

เหมือนที่คิดไว้ tensors จะมีค่าที่แตกต่างกัน

แต่ถ้าต้องการสร้าง tensors สุ่มสองตัวที่มีค่าเหมือนกันละ?


นั่นคือที่ torch.manual_seed(seed) เข้ามาใช้, ที่ seed เป็นจำนวนเต็ม (เช่น 42 แต่อาจเป็นอะไรก็ได้) ที่ใช้ในการกำหนดลักษณะของความสุ่ม



นั่นคือที่เอา  [`torch.manual_seed(seed)`](https://pytorch.org/docs/stable/generated/torch.manual_seed.html) เข้ามาใช้ ที่ seed เป็นจำนวนเต็ม (เช่น 42 แต่อาจเป็นอะไรก็ได้) ที่ใช้ในการกำหนด รหัส ของการสุ่ม

มาลองใช้กันดูโดยการสร้าง tensors สุ่มที่มีลักษณะการสุ่มที่แตกต่างกันบ้าง

In [ ]:
import torch
import random

-
RANDOM_SEED=2248 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.1106, 0.1814, 0.7274, 0.7250],
        [0.3682, 0.0088, 0.1625, 0.0876],
        [0.5171, 0.5276, 0.8105, 0.0022]])

Tensor D:
tensor([[0.1106, 0.1814, 0.7274, 0.7250],
        [0.3682, 0.0088, 0.1625, 0.0876],
        [0.5171, 0.5276, 0.8105, 0.0022]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])